-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 11:34:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`midia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`midia` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `tipo` ENUM('CD', 'DVD') NOT NULL,
  `data_gravacao` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`area_conhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`area_conhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tema_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tema_id`),
  INDEX `fk_area_conhecimento_tema1_idx` (`tema_id` ASC),
  CONSTRAINT `fk_area_conhecimento_tema1`
    FOREIGN KEY (`tema_id`)
    REFERENCES `biblioteca`.`tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livro` (
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `editora_id` INT NOT NULL,
  `ano` DATE NOT NULL,
  `edicao` INT NOT NULL,
  `num_pag` INT NOT NULL,
  `area_conhecimento_id` INT NOT NULL,
  PRIMARY KEY (`isbn`, `editora_id`, `area_conhecimento_id`),
  INDEX `fk_livro_editora1_idx` (`editora_id` ASC),
  INDEX `fk_livro_area_conhecimento1_idx` (`area_conhecimento_id` ASC),
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`editora_id`)
    REFERENCES `biblioteca`.`editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_area_conhecimento1`
    FOREIGN KEY (`area_conhecimento_id`)
    REFERENCES `biblioteca`.`area_conhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`revista` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `editora_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `edicao` INT NOT NULL,
  `num_pag` INT NOT NULL,
  PRIMARY KEY (`id`, `editora_id`),
  INDEX `fk_revista_editora1_idx` (`editora_id` ASC),
  CONSTRAINT `fk_revista_editora1`
    FOREIGN KEY (`editora_id`)
    REFERENCES `biblioteca`.`editora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`jornal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`jornal` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `edicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`cidade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`anal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`anal` (
  `id` INT NOT NULL,
  `tipo` ENUM('artigo', 'poster', 'resumo') NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `congresso` VARCHAR(45) NOT NULL,
  `ano_pub` DATE NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cidade_id`),
  INDEX `fk_anal_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_anal_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `biblioteca`.`cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`orientador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`orientador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `formacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tcc` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `autor_id` INT NOT NULL,
  `orientador_id` INT NOT NULL,
  `tipo` ENUM('monografia', 'tese', 'dissertacao') NOT NULL,
  `defesa` DATE NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autor_id`, `orientador_id`, `cidade_id`),
  INDEX `fk_tcc_autor1_idx` (`autor_id` ASC),
  INDEX `fk_tcc_orientador1_idx` (`orientador_id` ASC),
  INDEX `fk_tcc_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_tcc_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `biblioteca`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcc_orientador1`
    FOREIGN KEY (`orientador_id`)
    REFERENCES `biblioteca`.`orientador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcc_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `biblioteca`.`cidade` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor_has_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor_has_livro` (
  `autor_id` INT NOT NULL,
  `livro_isbn` INT NOT NULL,
  PRIMARY KEY (`autor_id`, `livro_isbn`),
  INDEX `fk_autor_has_livro_livro1_idx` (`livro_isbn` ASC),
  INDEX `fk_autor_has_livro_autor_idx` (`autor_id` ASC),
  CONSTRAINT `fk_autor_has_livro_autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `biblioteca`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_livro_livro1`
    FOREIGN KEY (`livro_isbn`)
    REFERENCES `biblioteca`.`livro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`anal_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`anal_has_autor` (
  `anal_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  PRIMARY KEY (`anal_id`, `autor_id`),
  INDEX `fk_anal_has_autor_autor1_idx` (`autor_id` ASC),
  INDEX `fk_anal_has_autor_anal1_idx` (`anal_id` ASC),
  CONSTRAINT `fk_anal_has_autor_anal1`
    FOREIGN KEY (`anal_id`)
    REFERENCES `biblioteca`.`anal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anal_has_autor_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `biblioteca`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`curso` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('graduacao', 'pos_graduacao') NOT NULL,
  `area_conhecimento_id` INT NOT NULL,
  `area_conhecimento_tema_id` INT NOT NULL,
  PRIMARY KEY (`id`, `area_conhecimento_id`, `area_conhecimento_tema_id`),
  INDEX `fk_curso_area_conhecimento1_idx` (`area_conhecimento_id` ASC, `area_conhecimento_tema_id` ASC),
  CONSTRAINT `fk_curso_area_conhecimento1`
    FOREIGN KEY (`area_conhecimento_id` , `area_conhecimento_tema_id`)
    REFERENCES `biblioteca`.`area_conhecimento` (`id` , `tema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
